INFO 2019-07-18 11:14:43,926 basehttp 154 "GET /admin/ HTTP/1.1" 200 8784
WARNING 2019-07-18 11:14:44,105 log 228 Not Found: /favicon.ico
WARNING 2019-07-18 11:14:44,106 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2187
INFO 2019-07-18 11:14:50,614 views 91 /polls/get_man/
INFO 2019-07-18 11:14:50,620 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 200 338
INFO 2019-07-18 11:14:50,645 basehttp 154 "GET /static/js/vue.min.js HTTP/1.1" 200 70998
INFO 2019-07-18 11:14:50,646 basehttp 154 "GET /static/js/man.js HTTP/1.1" 200 37
INFO 2019-07-18 11:14:50,659 basehttp 154 "GET /static/css/style.css HTTP/1.1" 304 0
INFO 2019-07-18 11:14:50,700 basehttp 154 "GET /static/images/background.png HTTP/1.1" 200 1724105
INFO 2019-07-18 11:18:08,187 views 91 /polls/get_man/
INFO 2019-07-18 11:18:08,195 views 92 False
INFO 2019-07-18 11:18:08,201 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 200 338
INFO 2019-07-18 11:18:08,237 basehttp 154 "GET /static/images/favicon.ico HTTP/1.1" 200 1459819
INFO 2019-07-18 11:19:47,825 views 91 /polls/get_man/
INFO 2019-07-18 11:19:47,825 views 92 False
INFO 2019-07-18 11:19:47,825 views 93 {'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'XUEHAOWENG', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\ŒÃ—ß∫¿', 'LOCALAPPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local', 'LOGONSERVER': '\\\\XUEHAOWENG', 'MYSQL': 'C:\\Mysql\\mysql-8.0.13-winx64\\bin', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\ŒÃ—ß∫¿\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Python\\Python36;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\shortcut;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\;D:\\Git\\cmd;D:\\wxh\\tools\\node\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Microsoft\\WindowsApps;D:\\wxh\\tools\\Microsoft VS Code\\bin;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\GitHubDesktop\\bin;D:\\shortcut;D:\\PyCharm 2019.1.3\\bin;;C:\\Mysql\\mysql-8.0.13-winx64\\bin;C:\\Program Files\\JetBrains\\PyCharm 2018.3.1\\bin;C:\\Python\\Python36\\Lib\\site-packages\\django;C:\\Python27\\Lib\\site-packages\\django;C:\\Python\\Python36\\;C:\\Python\\Python36\\Scripts;C:\\seleniumdirver\\chromedriver.exe;C:\\seleniumdirver\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming\\npm;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8e0a', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM': 'D:\\PyCharm 2019.1.3\\bin;', 'PYCHARM_DISPLAY_PORT': '4390', 'PYCHARM_HOSTED': '1', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'D:\\wxh\\mysite;D:\\wxh\\mysite\\static;D:\\PyCharm 2019.1.3\\helpers\\pycharm_matplotlib_backend;D:\\PyCharm 2019.1.3\\helpers\\pycharm_display', 'PYTHONUNBUFFERED': '1', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'USERDOMAIN': 'XUEHAOWENG', 'USERDOMAIN_ROAMINGPROFILE': 'XUEHAOWENG', 'USERNAME': 'ŒÃ—ß∫¿', 'USERPROFILE': 'C:\\Users\\ŒÃ—ß∫¿', 'WINDIR': 'C:\\WINDOWS', 'DJANGO_SETTINGS_MODULE': 'mysite.settings', 'RUN_MAIN': 'true', 'SERVER_NAME': 'xuehaoWeng', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '9000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/polls/get_man/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:9000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_PRAGMA': 'no-cache', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.9', 'HTTP_COOKIE': 'csrftoken=lniJGlOmYFoJl73WncIC04fLMHq7LeE8gJvyI068r4UoPIaqa9Hhjd6ZLxW03bgc; sessionid=8ukmepfgnk98ok5v8467337rgnhr9f90', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000002107CE002B0>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}
INFO 2019-07-18 11:19:47,840 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 200 338
INFO 2019-07-18 11:19:47,851 basehttp 154 "GET /static/css/style.css HTTP/1.1" 200 203
INFO 2019-07-18 11:19:47,852 basehttp 154 "GET /static/js/man.js HTTP/1.1" 200 37
INFO 2019-07-18 11:19:47,853 basehttp 154 "GET /static/js/vue.min.js HTTP/1.1" 200 70998
INFO 2019-07-18 11:19:47,872 basehttp 154 "GET /static/images/background.png HTTP/1.1" 200 1724105
INFO 2019-07-18 11:19:47,895 basehttp 154 "GET /static/images/favicon.ico HTTP/1.1" 200 1459819
INFO 2019-07-18 11:21:19,336 views 92 «Î«Û¬∑æ∂£∫/polls/get_man/
INFO 2019-07-18 11:21:19,336 views 93 «Î«Û «∑Ò «https£∫False
INFO 2019-07-18 11:21:19,336 views 94 «Î«Ûheaders:{'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'XUEHAOWENG', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\ŒÃ—ß∫¿', 'LOCALAPPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local', 'LOGONSERVER': '\\\\XUEHAOWENG', 'MYSQL': 'C:\\Mysql\\mysql-8.0.13-winx64\\bin', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\ŒÃ—ß∫¿\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Python\\Python36;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\shortcut;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\;D:\\Git\\cmd;D:\\wxh\\tools\\node\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Microsoft\\WindowsApps;D:\\wxh\\tools\\Microsoft VS Code\\bin;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\GitHubDesktop\\bin;D:\\shortcut;D:\\PyCharm 2019.1.3\\bin;;C:\\Mysql\\mysql-8.0.13-winx64\\bin;C:\\Program Files\\JetBrains\\PyCharm 2018.3.1\\bin;C:\\Python\\Python36\\Lib\\site-packages\\django;C:\\Python27\\Lib\\site-packages\\django;C:\\Python\\Python36\\;C:\\Python\\Python36\\Scripts;C:\\seleniumdirver\\chromedriver.exe;C:\\seleniumdirver\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming\\npm;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8e0a', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM': 'D:\\PyCharm 2019.1.3\\bin;', 'PYCHARM_DISPLAY_PORT': '4390', 'PYCHARM_HOSTED': '1', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'D:\\wxh\\mysite;D:\\wxh\\mysite\\static;D:\\PyCharm 2019.1.3\\helpers\\pycharm_matplotlib_backend;D:\\PyCharm 2019.1.3\\helpers\\pycharm_display', 'PYTHONUNBUFFERED': '1', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'USERDOMAIN': 'XUEHAOWENG', 'USERDOMAIN_ROAMINGPROFILE': 'XUEHAOWENG', 'USERNAME': 'ŒÃ—ß∫¿', 'USERPROFILE': 'C:\\Users\\ŒÃ—ß∫¿', 'WINDIR': 'C:\\WINDOWS', 'DJANGO_SETTINGS_MODULE': 'mysite.settings', 'RUN_MAIN': 'true', 'SERVER_NAME': 'xuehaoWeng', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '9000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/polls/get_man/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:9000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_PRAGMA': 'no-cache', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.9', 'HTTP_COOKIE': 'csrftoken=lniJGlOmYFoJl73WncIC04fLMHq7LeE8gJvyI068r4UoPIaqa9Hhjd6ZLxW03bgc; sessionid=8ukmepfgnk98ok5v8467337rgnhr9f90', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000002577BAE2860>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}
INFO 2019-07-18 11:21:19,344 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 200 338
INFO 2019-07-18 11:21:19,357 basehttp 154 "GET /static/css/style.css HTTP/1.1" 200 203
INFO 2019-07-18 11:21:19,358 basehttp 154 "GET /static/js/man.js HTTP/1.1" 200 37
INFO 2019-07-18 11:21:19,358 basehttp 154 "GET /static/js/vue.min.js HTTP/1.1" 200 70998
INFO 2019-07-18 11:21:19,381 basehttp 154 "GET /static/images/background.png HTTP/1.1" 200 1724105
INFO 2019-07-18 11:21:19,404 basehttp 154 "GET /static/images/favicon.ico HTTP/1.1" 200 1459819
INFO 2019-07-18 11:21:47,987 views 92 «Î«Û¬∑æ∂£∫/polls/get_man/
INFO 2019-07-18 11:21:47,987 views 93 «Î«Û «∑Ò «https£∫False
INFO 2019-07-18 11:21:47,987 views 94 «Î«Ûheaders:{'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'XUEHAOWENG', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\ŒÃ—ß∫¿', 'LOCALAPPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local', 'LOGONSERVER': '\\\\XUEHAOWENG', 'MYSQL': 'C:\\Mysql\\mysql-8.0.13-winx64\\bin', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\ŒÃ—ß∫¿\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Python\\Python36;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\shortcut;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\;D:\\Git\\cmd;D:\\wxh\\tools\\node\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Microsoft\\WindowsApps;D:\\wxh\\tools\\Microsoft VS Code\\bin;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\GitHubDesktop\\bin;D:\\shortcut;D:\\PyCharm 2019.1.3\\bin;;C:\\Mysql\\mysql-8.0.13-winx64\\bin;C:\\Program Files\\JetBrains\\PyCharm 2018.3.1\\bin;C:\\Python\\Python36\\Lib\\site-packages\\django;C:\\Python27\\Lib\\site-packages\\django;C:\\Python\\Python36\\;C:\\Python\\Python36\\Scripts;C:\\seleniumdirver\\chromedriver.exe;C:\\seleniumdirver\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming\\npm;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8e0a', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM': 'D:\\PyCharm 2019.1.3\\bin;', 'PYCHARM_DISPLAY_PORT': '4390', 'PYCHARM_HOSTED': '1', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'D:\\wxh\\mysite;D:\\wxh\\mysite\\static;D:\\PyCharm 2019.1.3\\helpers\\pycharm_matplotlib_backend;D:\\PyCharm 2019.1.3\\helpers\\pycharm_display', 'PYTHONUNBUFFERED': '1', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'USERDOMAIN': 'XUEHAOWENG', 'USERDOMAIN_ROAMINGPROFILE': 'XUEHAOWENG', 'USERNAME': 'ŒÃ—ß∫¿', 'USERPROFILE': 'C:\\Users\\ŒÃ—ß∫¿', 'WINDIR': 'C:\\WINDOWS', 'DJANGO_SETTINGS_MODULE': 'mysite.settings', 'RUN_MAIN': 'true', 'SERVER_NAME': 'xuehaoWeng', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '9000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/polls/get_man/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:9000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_CACHE_CONTROL': 'max-age=0', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.9', 'HTTP_COOKIE': 'csrftoken=lniJGlOmYFoJl73WncIC04fLMHq7LeE8gJvyI068r4UoPIaqa9Hhjd6ZLxW03bgc; sessionid=8ukmepfgnk98ok5v8467337rgnhr9f90', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x000002577BF09F60>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}
INFO 2019-07-18 11:21:47,992 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 200 338
INFO 2019-07-18 11:21:48,050 basehttp 154 "GET /static/images/favicon.ico HTTP/1.1" 200 1459819
INFO 2019-07-18 11:22:57,820 views 92 «Î«Û¬∑æ∂£∫/polls/get_man/
INFO 2019-07-18 11:22:57,821 views 93 «Î«Û «∑Ò «https£∫False
INFO 2019-07-18 11:22:57,821 views 94 «Î«Ûheaders:{'ALLUSERSPROFILE': 'C:\\ProgramData', 'APPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming', 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files', 'COMPUTERNAME': 'XUEHAOWENG', 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe', 'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\Users\\ŒÃ—ß∫¿', 'LOCALAPPDATA': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local', 'LOGONSERVER': '\\\\XUEHAOWENG', 'MYSQL': 'C:\\Mysql\\mysql-8.0.13-winx64\\bin', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\Users\\ŒÃ—ß∫¿\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\Python\\Python36;C:\\Python27\\;C:\\Python27\\Scripts;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\shortcut;C:\\Program Files\\Microsoft VS Code\\bin;C:\\Program Files\\;D:\\Git\\cmd;D:\\wxh\\tools\\node\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\Scripts\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Microsoft\\WindowsApps;D:\\wxh\\tools\\Microsoft VS Code\\bin;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\GitHubDesktop\\bin;D:\\shortcut;D:\\PyCharm 2019.1.3\\bin;;C:\\Mysql\\mysql-8.0.13-winx64\\bin;C:\\Program Files\\JetBrains\\PyCharm 2018.3.1\\bin;C:\\Python\\Python36\\Lib\\site-packages\\django;C:\\Python27\\Lib\\site-packages\\django;C:\\Python\\Python36\\;C:\\Python\\Python36\\Scripts;C:\\seleniumdirver\\chromedriver.exe;C:\\seleniumdirver\\phantomjs-2.1.1-windows\\bin\\phantomjs.exe;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Roaming\\npm;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs;C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\numpy\\.libs', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 142 Stepping 10, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8e0a', 'PROGRAMDATA': 'C:\\ProgramData', 'PROGRAMFILES': 'C:\\Program Files', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROGRAMW6432': 'C:\\Program Files', 'PSMODULEPATH': 'C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules', 'PUBLIC': 'C:\\Users\\Public', 'PYCHARM': 'D:\\PyCharm 2019.1.3\\bin;', 'PYCHARM_DISPLAY_PORT': '4390', 'PYCHARM_HOSTED': '1', 'PYTHONIOENCODING': 'UTF-8', 'PYTHONPATH': 'D:\\wxh\\mysite;D:\\wxh\\mysite\\static;D:\\PyCharm 2019.1.3\\helpers\\pycharm_matplotlib_backend;D:\\PyCharm 2019.1.3\\helpers\\pycharm_display', 'PYTHONUNBUFFERED': '1', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\WINDOWS', 'TEMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'TMP': 'C:\\Users\\ŒÃ—ß∫¿\\AppData\\Local\\Temp', 'USERDOMAIN': 'XUEHAOWENG', 'USERDOMAIN_ROAMINGPROFILE': 'XUEHAOWENG', 'USERNAME': 'ŒÃ—ß∫¿', 'USERPROFILE': 'C:\\Users\\ŒÃ—ß∫¿', 'WINDIR': 'C:\\WINDOWS', 'DJANGO_SETTINGS_MODULE': 'mysite.settings', 'RUN_MAIN': 'true', 'SERVER_NAME': 'xuehaoWeng', 'GATEWAY_INTERFACE': 'CGI/1.1', 'SERVER_PORT': '9000', 'REMOTE_HOST': '', 'CONTENT_LENGTH': '', 'SCRIPT_NAME': '', 'SERVER_PROTOCOL': 'HTTP/1.1', 'SERVER_SOFTWARE': 'WSGIServer/0.2', 'REQUEST_METHOD': 'GET', 'PATH_INFO': '/polls/get_man/', 'QUERY_STRING': '', 'REMOTE_ADDR': '127.0.0.1', 'CONTENT_TYPE': 'text/plain', 'HTTP_HOST': '127.0.0.1:9000', 'HTTP_CONNECTION': 'keep-alive', 'HTTP_CACHE_CONTROL': 'max-age=0', 'HTTP_UPGRADE_INSECURE_REQUESTS': '1', 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36', 'HTTP_ACCEPT': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.9', 'HTTP_COOKIE': 'csrftoken=lniJGlOmYFoJl73WncIC04fLMHq7LeE8gJvyI068r4UoPIaqa9Hhjd6ZLxW03bgc; sessionid=8ukmepfgnk98ok5v8467337rgnhr9f90', 'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x00000258AF5B95C0>, 'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>, 'wsgi.version': (1, 0), 'wsgi.run_once': False, 'wsgi.url_scheme': 'http', 'wsgi.multithread': True, 'wsgi.multiprocess': False, 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>}
ERROR 2019-07-18 11:22:57,859 log 228 Internal Server Error: /polls/get_man/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\wxh\mysite\apps\polls\views.py", line 95, in get
    logger.info(request.headers)
AttributeError: 'WSGIRequest' object has no attribute 'headers'
ERROR 2019-07-18 11:22:57,861 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 500 78005
WARNING 2019-07-18 11:22:58,038 log 228 Not Found: /favicon.ico
WARNING 2019-07-18 11:22:58,039 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2187
ERROR 2019-07-18 11:23:53,984 log 228 Internal Server Error: /polls/get_man/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\wxh\mysite\apps\polls\views.py", line 101, in get
    values.sort()
AttributeError: 'dict_items' object has no attribute 'sort'
ERROR 2019-07-18 11:23:53,986 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 500 83332
INFO 2019-07-18 11:25:43,534 basehttp 154 "GET /polls/get_man/ HTTP/1.1" 200 6607
WARNING 2019-07-19 10:46:28,649 log 228 Not Found: /
WARNING 2019-07-19 10:46:28,649 basehttp 154 "GET / HTTP/1.1" 404 2242
WARNING 2019-07-19 10:46:28,768 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 10:46:28,769 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
INFO 2019-07-19 10:46:41,752 basehttp 154 "GET /books/search_form HTTP/1.1" 301 0
INFO 2019-07-19 10:46:41,762 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 183
INFO 2019-07-19 10:50:09,022 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
WARNING 2019-07-19 10:50:09,042 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 10:50:09,042 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
ERROR 2019-07-19 10:50:10,661 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.books.views.search didn't return an HttpResponse object. It returned None instead.
ERROR 2019-07-19 10:50:10,662 basehttp 154 "GET /books/search/?q= HTTP/1.1" 500 60464
ERROR 2019-07-19 10:50:17,920 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 137, in _get_response
    "returned None instead." % (callback.__module__, view_name)
ValueError: The view apps.books.views.search didn't return an HttpResponse object. It returned None instead.
ERROR 2019-07-19 10:50:17,921 basehttp 154 "GET /books/search/?q=q HTTP/1.1" 500 60470
INFO 2019-07-19 10:50:41,262 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
INFO 2019-07-19 10:50:43,676 basehttp 154 "GET /books/search/?q=q HTTP/1.1" 200 21
INFO 2019-07-19 10:50:53,550 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 20
INFO 2019-07-19 10:52:06,239 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
INFO 2019-07-19 10:52:07,416 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
WARNING 2019-07-19 10:52:07,436 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 10:52:07,436 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
INFO 2019-07-19 10:52:09,071 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 20
INFO 2019-07-19 10:53:00,334 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 20
WARNING 2019-07-19 10:53:00,351 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 10:53:00,352 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
INFO 2019-07-19 10:53:05,051 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 26
INFO 2019-07-19 10:53:08,615 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 20
INFO 2019-07-19 10:53:37,036 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
WARNING 2019-07-19 10:53:37,081 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 10:53:37,082 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
INFO 2019-07-19 10:53:38,631 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 20
INFO 2019-07-19 10:53:43,414 basehttp 154 "GET /books/search/?q=. HTTP/1.1" 200 21
INFO 2019-07-19 10:57:17,391 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
WARNING 2019-07-19 10:57:17,410 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 10:57:17,410 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
INFO 2019-07-19 10:57:20,183 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 97
INFO 2019-07-19 11:00:48,909 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 114
INFO 2019-07-19 11:06:35,414 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 28
INFO 2019-07-19 11:06:39,352 basehttp 154 "GET /books/search/?q=weng HTTP/1.1" 200 95
INFO 2019-07-19 11:07:43,257 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
INFO 2019-07-19 11:07:45,540 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 142
INFO 2019-07-19 11:07:52,953 basehttp 154 "GET /books/search/?q=%E5%9F%9F HTTP/1.1" 200 139
INFO 2019-07-19 11:07:57,841 basehttp 154 "GET /books/search/?q=weng HTTP/1.1" 200 75
INFO 2019-07-19 11:08:30,320 basehttp 154 "GET /books/search/?q=weng HTTP/1.1" 200 75
INFO 2019-07-19 11:08:31,347 basehttp 154 "GET /books/search/?q=weng HTTP/1.1" 200 75
INFO 2019-07-19 11:08:33,153 basehttp 154 "GET /books/search/?q=weng HTTP/1.1" 200 75
WARNING 2019-07-19 11:08:33,174 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 11:08:33,174 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
INFO 2019-07-19 11:08:38,262 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 197
WARNING 2019-07-19 11:08:38,280 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 11:08:38,280 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2293
INFO 2019-07-19 11:08:42,690 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 196
INFO 2019-07-19 11:09:19,898 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 28
INFO 2019-07-19 11:15:23,106 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 257
INFO 2019-07-19 11:16:43,915 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 198
INFO 2019-07-19 11:16:47,533 basehttp 154 "GET /books/search/?q=python%E7%9A%84app%E5%BC%80%E5%8F%91 HTTP/1.1" 200 89
INFO 2019-07-19 11:16:53,369 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 142
INFO 2019-07-19 11:16:56,827 basehttp 154 "GET /books/search/?q= HTTP/1.1" 200 257
INFO 2019-07-19 11:21:26,078 basehttp 154 "GET /books/search_form/ HTTP/1.1" 200 198
WARNING 2019-07-19 16:26:40,071 log 228 Not Found: /
WARNING 2019-07-19 16:26:40,072 basehttp 154 "GET / HTTP/1.1" 404 2349
WARNING 2019-07-19 16:26:40,202 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 16:26:40,203 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2400
WARNING 2019-07-19 16:26:46,479 log 228 Not Found: /books/search_form/
WARNING 2019-07-19 16:26:46,480 basehttp 154 "GET /books/search_form/ HTTP/1.1" 404 2499
INFO 2019-07-19 16:26:50,574 basehttp 154 "GET /books/search HTTP/1.1" 301 0
ERROR 2019-07-19 16:26:50,618 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\haystack\generic_views.py", line 126, in get
    return self.form_valid(form)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\haystack\generic_views.py", line 83, in form_valid
    'object_list': self.queryset
  File "D:\wxh\mysite\apps\books\views.py", line 33, in get_context_data
    form_data = mySearchView.get_form_kwargs()['q']
KeyError: 'q'
ERROR 2019-07-19 16:26:50,619 basehttp 154 "GET /books/search/ HTTP/1.1" 500 87146
ERROR 2019-07-19 16:27:04,833 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'search' not found. 'search' is not a valid view function or pattern name.
ERROR 2019-07-19 16:27:04,835 basehttp 154 "GET /books/search/ HTTP/1.1" 500 117349
INFO 2019-07-19 16:28:08,861 basehttp 154 "GET /books/search/ HTTP/1.1" 200 6
ERROR 2019-07-19 16:28:37,740 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\wxh\mysite\apps\books\views.py", line 34, in get
    return render_to_response('search_form.html', {'error': True})
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'search' not found. 'search' is not a valid view function or pattern name.
ERROR 2019-07-19 16:28:37,743 basehttp 154 "GET /books/search/ HTTP/1.1" 500 127461
ERROR 2019-07-19 16:29:47,346 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\wxh\mysite\apps\books\views.py", line 34, in get
    return render_to_response('search_form.html', {'error': True})
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '' not found. '' is not a valid view function or pattern name.
ERROR 2019-07-19 16:29:47,347 basehttp 154 "GET /books/search/ HTTP/1.1" 500 127315
ERROR 2019-07-19 16:29:54,974 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\wxh\mysite\apps\books\views.py", line 34, in get
    return render_to_response('search_form.html', {'error': True})
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'search' not found. 'search' is not a valid view function or pattern name.
ERROR 2019-07-19 16:29:54,976 basehttp 154 "GET /books/search/ HTTP/1.1" 500 127461
ERROR 2019-07-19 16:30:01,203 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: __init__() takes 1 positional argument but 2 were given
ERROR 2019-07-19 16:30:01,205 basehttp 154 "GET /books/search/ HTTP/1.1" 500 65937
WARNING 2019-07-19 16:30:01,275 log 228 Not Found: /favicon.ico
WARNING 2019-07-19 16:30:01,276 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2400
INFO 2019-07-19 16:30:24,420 basehttp 154 "GET /books/search/ HTTP/1.1" 200 257
ERROR 2019-07-19 16:30:26,852 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\wxh\mysite\apps\books\views.py", line 32, in get
    {'books': books, 'query': q})
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'search_form' not found. 'search_form' is not a valid view function or pattern name.
ERROR 2019-07-19 16:30:26,855 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 500 129617
ERROR 2019-07-19 16:30:32,501 log 228 Internal Server Error: /books/search/
Traceback (most recent call last):
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\handlers\base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\views\generic\base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\wxh\mysite\apps\books\views.py", line 32, in get
    {'books': books, 'query': q})
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\shortcuts.py", line 27, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\template\defaulttags.py", line 442, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\base.py", line 90, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "C:\Users\ŒÃ—ß∫¿\AppData\Local\Programs\Python\Python36\lib\site-packages\django\urls\resolvers.py", line 622, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'search_form' not found. 'search_form' is not a valid view function or pattern name.
ERROR 2019-07-19 16:30:32,503 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 500 129617
INFO 2019-07-19 16:31:31,491 basehttp 154 "GET /books/search/ HTTP/1.1" 200 257
INFO 2019-07-19 16:31:33,811 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 314
INFO 2019-07-19 16:31:36,566 basehttp 154 "GET /books/search_form/?q=weng HTTP/1.1" 200 198
INFO 2019-07-19 16:31:56,343 basehttp 154 "GET /books/search/?q=%E5%9F%9F%E5%90%8D HTTP/1.1" 200 77
INFO 2019-07-19 16:32:05,860 basehttp 154 "GET /books/search/?q=%E4%B9%A6%E7%B1%8D HTTP/1.1" 200 77
